### ISSUE TITLE
New Folder naming not working correctly

### ISSUE THREAD

**Issue by Gitoffthelawn** [kashiif/edit-bookmark-plus#5]
When creating a new folder by pressing the New Folder button, the user has only about 500msec to enter the name.  After about 500msec, the folder loses focus, and whatever is being entered for the name is ignored.

The user has to then manually double-click on the new folder and name it.

**Comment by kashiif** [comment]
I am unable to reproduce this behavior. I tried on Firefox 40 and 41 on Windows.

Can you please mention the firefox version and whether you are using it on Windows or Linux. Also it would be helpful if you list the steps for me to able to see this bug.

**Comment by Gitoffthelawn** [comment]
Let's see... May 20th... that would have been Firefox 38.0.1 on Windows 7 SP1.

Steps to reproduce with that software:
1. Create new bookmark by clicking on the star toolbar button.
2. Click it again to open Edit Bookmark (Plus).
3. Click on New Folder.

Testing on Firefox 40.0.3 in Windows 7 SP1 no longer shows this bug.

**Comment by kashiif** [comment]
Thank you  @Gitoffthelawn

**Comment by kashiif** [comment]
Note To Self: Tried on FF37 and FF38 but the bug did not reproduce
